name: Build and Test with .NET

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
        submodules: recursive
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
  build:
    name: Build and Upload
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
        submodules: recursive
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet publish --no-restore -c Release -o "${{github.workspace}}/Builds"
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: FitbitWebOSC
        # A file, directory or wildcard pattern that describes what to upload
        path: ${{github.workspace}}/Builds/FitbitWebOSC.dll
    
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{secrets.GITHUB_TOKEN}}
        automatic_release_tag: latest
        prerelease: true
        title: Development Build
        files: ${{github.workspace}}/Builds/FitbitWebOSC.dll
